"""
auth.py

Authentication routes. The login flow is worth explaining:

1. Client fetches the user's salt (public endpoint, no auth required)
2. Client derives an auth verifier from password + salt using PBKDF2
3. Client sends email + verifier (NOT the password) to /login
4. We compare against the stored verifier using constant-time comparison
5. On match, we issue a short-lived JWT access token + refresh token

The verifier is separate from the encryption key. Even if this server were
compromised and the verifier stolen, it cannot decrypt notes — the encryption
key is derived differently and never transmitted.
"""

import uuid
import hashlib
import hmac
import os
from datetime import datetime, timedelta, timezone

import aiosqlite
from fastapi import APIRouter, Depends, HTTPException, Request, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel, EmailStr
import jwt

from app.db.database import get_db

router = APIRouter()
security = HTTPBearer()

JWT_SECRET = os.getenv("JWT_SECRET", "change-this-in-production-please")
JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 15
REFRESH_TOKEN_EXPIRE_DAYS = 30


# --- Schemas ---

class RegisterRequest(BaseModel):
    email: EmailStr
    salt: str       # base64 salt generated by client
    verifier: str   # PBKDF2-derived auth key, NOT the password


class LoginRequest(BaseModel):
    email: EmailStr
    verifier: str


class RefreshRequest(BaseModel):
    refresh_token: str


# --- Helpers ---

def create_access_token(user_id: str) -> str:
    expires = datetime.now(timezone.utc) + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    return jwt.encode({"sub": user_id, "exp": expires}, JWT_SECRET, algorithm=JWT_ALGORITHM)


def create_refresh_token() -> str:
    return uuid.uuid4().hex + uuid.uuid4().hex  # 64 char random token


def hash_token(token: str) -> str:
    return hashlib.sha256(token.encode()).hexdigest()


def constant_time_compare(a: str, b: str) -> bool:
    """Prevents timing attacks when comparing secrets."""
    return hmac.compare_digest(a.encode(), b.encode())


async def get_current_user(
    credentials: HTTPAuthorizationCredentials = Depends(security),
    db: aiosqlite.Connection = Depends(get_db),
) -> dict:
    try:
        payload = jwt.decode(credentials.credentials, JWT_SECRET, algorithms=[JWT_ALGORITHM])
        user_id: str = payload.get("sub")
        if not user_id:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token")
    except jwt.ExpiredSignatureError:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Token expired")
    except jwt.PyJWTError:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token")

    async with db.execute("SELECT * FROM users WHERE id = ?", (user_id,)) as cur:
        user = await cur.fetchone()
    if not user:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="User not found")

    return dict(user)


async def log_event(db, user_id: str, event: str, ip: str, metadata: str = None):
    await db.execute(
        "INSERT INTO audit_log (user_id, event, ip_address, metadata) VALUES (?, ?, ?, ?)",
        (user_id, event, ip, metadata)
    )


# --- Routes ---

@router.get("/salt")
async def get_salt(email: str, db: aiosqlite.Connection = Depends(get_db)):
    """
    Public endpoint — returns the user's salt.
    The client needs this before it can derive keys for login.
    We don't reveal whether the email exists to prevent enumeration.
    """
    async with db.execute("SELECT salt FROM users WHERE email = ?", (email.lower(),)) as cur:
        row = await cur.fetchone()

    if not row:
        # Return a deterministic fake salt to prevent user enumeration
        fake_salt = hashlib.sha256(email.encode() + b"nosuchuser").hexdigest()
        return {"salt": fake_salt}

    return {"salt": row["salt"]}


@router.post("/register", status_code=status.HTTP_201_CREATED)
async def register(
    body: RegisterRequest,
    request: Request,
    db: aiosqlite.Connection = Depends(get_db),
):
    email = body.email.lower()

    async with db.execute("SELECT id FROM users WHERE email = ?", (email,)) as cur:
        if await cur.fetchone():
            raise HTTPException(status_code=400, detail="Email already registered")

    user_id = str(uuid.uuid4())
    await db.execute(
        "INSERT INTO users (id, email, salt, verifier) VALUES (?, ?, ?, ?)",
        (user_id, email, body.salt, body.verifier)
    )
    await log_event(db, user_id, "register", request.client.host if request.client else "")
    await db.commit()

    return {"message": "Account created"}


@router.post("/login")
async def login(
    body: LoginRequest,
    request: Request,
    db: aiosqlite.Connection = Depends(get_db),
):
    email = body.email.lower()
    ip = request.client.host if request.client else ""

    async with db.execute("SELECT * FROM users WHERE email = ?", (email,)) as cur:
        user = await cur.fetchone()

    # Constant-time comparison regardless of whether user exists
    stored_verifier = dict(user)["verifier"] if user else "x" * 64
    if not user or not constant_time_compare(stored_verifier, body.verifier):
        raise HTTPException(status_code=401, detail="Invalid credentials")

    user = dict(user)
    access_token = create_access_token(user["id"])
    refresh_token = create_refresh_token()
    token_hash = hash_token(refresh_token)

    session_id = str(uuid.uuid4())
    expires_at = (datetime.now(timezone.utc) + timedelta(days=REFRESH_TOKEN_EXPIRE_DAYS)).isoformat()
    device_name = request.headers.get("User-Agent", "Unknown")[:80]

    await db.execute(
        """INSERT INTO sessions (id, user_id, token_hash, device_name, ip_address, expires_at)
           VALUES (?, ?, ?, ?, ?, ?)""",
        (session_id, user["id"], token_hash, device_name, ip, expires_at)
    )
    await log_event(db, user["id"], "login", ip)
    await db.commit()

    return {
        "access_token": access_token,
        "refresh_token": refresh_token,
        "user_id": user["id"],
        "email": user["email"],
        "token_type": "bearer",
    }


@router.post("/refresh")
async def refresh_token(
    body: RefreshRequest,
    db: aiosqlite.Connection = Depends(get_db),
):
    token_hash = hash_token(body.refresh_token)

    async with db.execute(
        """SELECT s.*, u.id as uid FROM sessions s
           JOIN users u ON s.user_id = u.id
           WHERE s.token_hash = ? AND s.expires_at > datetime('now')""",
        (token_hash,)
    ) as cur:
        session = await cur.fetchone()

    if not session:
        raise HTTPException(status_code=401, detail="Invalid or expired refresh token")

    session = dict(session)
    new_access = create_access_token(session["user_id"])

    # Update last_active
    await db.execute(
        "UPDATE sessions SET last_active = datetime('now') WHERE token_hash = ?",
        (token_hash,)
    )
    await db.commit()

    return {"access_token": new_access, "token_type": "bearer"}


@router.post("/logout")
async def logout(
    current_user: dict = Depends(get_current_user),
    db: aiosqlite.Connection = Depends(get_db),
):
    # In a real implementation we'd invalidate the specific session token here.
    # For now, we log the event and the short JWT lifetime handles expiry.
    await log_event(db, current_user["id"], "logout", "")
    await db.commit()
    return {"message": "Logged out"}
